config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :instruments, only: %i[index show]
  resources :users, only: %i[index] do
    resources :applied_instruments, only: %i[index new create]
  end

  get 'profile/check_info', to: 'users#check_info', as: 'check_info'
  post 'profile/checked', to: 'users#checked'
  get '/profile/:id', to: 'users#profile', as: 'profile'

  resources :applied_instruments, only: :show do
    post 'finish_instrument', to: 'applied_instruments#finish_instrument'
    resources :evaluated_answers, only: %i[new create]
  end

  resources :evaluated_answers, only: %i[edit update]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @patients = policy_scope(User).where(role: 1)
  end

  def show
    @patient = User.find(params[:id])

    authorize @patient
  end
end

app/views/profiles/index.html.erb
<div class="container mx-auto">
  <h1 class="text-4xl text-center">Lista de Pacientes</h1>

    <div class="users-grid-wrapper">
      <% @patients.each_with_index do |patient, index| %>
        <div class="patient-grid-item"><%= index + 1 %></div>
        <%= link_to profile_path(patient) do%>
          <div class="patient-grid-item"><%= patient.first_name %> <%= patient.last_name %></div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/profiles/show.html.erb
<div class="patient-first_name">
  <h1><%= @patient.first_name %> <%= @patient.last_name %></h1>

  <p><strong>CEP:</strong> <%= @patient.registration_number %></p>
  <p><strong>Data de Nascimento:</strong> <%= @patient.birth_date %></p>

  <%= link_to "Aplicar Novo Instrumento em #{@patient.first_name}", new_profile_applied_instrument_path(@patient) %>

  <h3>Instrumentos Aplicados:</h3>

  <div class="instrument-grid-wrapper">
    <% @patient.applied_instruments.each_with_index do |applied_instrument, index| %>
      <%= link_to applied_instrument_path(applied_instrument) do%>
        <div class="instrument-grid-item"><%= applied_instrument.instrument.title %></div>
      <% end %>
      <div class="instrument-grid-item"><%= applied_instrument.status %></div>
    <% end %>
  </div>
</div>