config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :instruments, only: %i[index show]
  resources :users, only: %i[index] do
    resources :applied_instruments, only: %i[index new create]
  end

  get 'profile/check_info', to: 'users#check_info', as: 'check_info'
  post 'profile/checked', to: 'users#checked'
  get '/profile/:id', to: 'users#profile', as: 'profile'

  resources :applied_instruments, only: :show do
    post 'finish_instrument', to: 'applied_instruments#finish_instrument'
    resources :evaluated_answers, only: %i[new create]
  end

  resources :evaluated_answers, only: %i[edit update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :applied_instruments, dependent: :destroy
  has_many :evaluated_answers, dependent: :destroy

  # Validations
  validates :birth_date, presence: true, if: -> { requires_info? }
  validates :registration_number, presence: true, if: -> { requires_info? }

  # Enums
  enum role: {
    psychologist: 0, # usuário psicólogo
    patient: 1 # paciente avaliado
  }

  def translated_role
    case role.to_sym
    when :psychologist then "Psicólogo"
    when :patient then "Avaliado"
    end
  end

  private

  def requires_info?
    patient?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @patients = policy_scope(User).where(role: 1)
  end

  def profile
    @patient = User.find(params[:id])

    authorize @patient
  end

  def check_info
    authorize User
  end

  def checked
    if current_user.first_name == params[:first_name] &&
       current_user.last_name == params[:last_name] &&
       current_user.email == params[:email] && current_user.birth_date == params[:birth_date].to_date &&
       current_user.registration_number == params[:registration_number]

      redirect_to profile_path(current_user)
    else
      render :check_info, alert: 'Entre com o perfil correto!'
    end

    authorize current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/check_info.html.erb
<div class="container list">
  <div class="d-flex">
    <%= link_to "<i class='fa-solid fa-right-from-bracket'></i>".html_safe, destroy_user_session_path, data: { turbo_method: :delete }, class: 'back-link' %>
    <h1>Atenção! Você deve estar logado com a conta correta!</h1>
  </div>

  <%= form_with url: profile_checked_path, method: :post, data: { turbo: false }, html: { class: 'form'  } do |f| %>
    <div class="form-inputs">
      <%= f.label :first_name, "Nome" %>
      <%= f.text_field :first_name %>
    </div>
    <div class="form-inputs">
      <%= f.label :last_name, "Sobrenome" %>
      <%= f.text_field :last_name %>
    </div>
    <div class="form-inputs">
      <%= f.label :email, "Email" %>
      <%= f.text_field :email %>
    </div>
    <div class="form-inputs">
      <div class="birth-date">
        <%= f.label :birth_date, "Data de Nascimento" %>
        <%= f.date_field :birth_date %>
      </div>
    </div>
    <div class="form-inputs">
      <%= f.label :registration_number, "CEP" %>
      <%= f.text_field :registration_number %>
    </div>

    <%= f.submit 'Checar Perfil', class: 'btn-form px-5' %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container list">
  <div class="d-flex">
    <%= link_to root_path, class: 'back-link' do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
    <% end %>
    <h1>Lista de Avaliados</h1>
  </div>

  <div class="table-grid-wrapper">
    <% @patients.each_with_index do |patient, index| %>
      <div class="table-grid-item first"><%= index + 1 %></div>
      <%= link_to profile_path(patient) do%>
        <div class="table-grid-item second">
          <%= patient.first_name %> <%= patient.last_name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <div class="d-flex mb-3">
    <%= link_to root_path, class: 'back-link' do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
    <% end %>
    <h1>Perfil de <%= @patient.first_name %></h1>
  </div>

  <div class="profile-wrapper">
    <div class="profile-info">
      <div>
        <p><strong>Nome Completo:</strong> <%= @patient.first_name %> <%= @patient.last_name %></p>
        <p><strong>E-mail:</strong> <%= @patient.email %></p>
        <p><strong>CEP:</strong> <%= @patient.registration_number %></p>
        <p><strong>Data de Nascimento:</strong> <%= @patient.birth_date.strftime("%d/%m/%Y") %></p>
      </div>

      <% if current_user.psychologist? %>
        <%= link_to "Aplicar Novo Instrumento em #{@patient.first_name}", new_user_applied_instrument_path(@patient), class: 'btn-profile' %>
      <% end %>
    </div>

    <div class="profile-instruments">
      <h3>Instrumentos Aplicados:</h3>

      <div class="profile-grid-wrapper">
        <% @patient.applied_instruments.each_with_index do |applied_instrument, index| %>
          <%= link_to applied_instrument_path(applied_instrument) do%>
            <div class="profile-grid-item first-prof"><%= applied_instrument.instrument.title %></div>
          <% end %>
          <div class="profile-grid-item second-prof">
            <%= translate_status(applied_instrument.status) %>
            <i class="fa-solid fa-check <%= 'd-none' if applied_instrument.pending? %>"></i>
          </div>
        <% end %>
      </div>
    </div>

  </div>


</div>

app/views/users/show.html.erb
<div class="patient-first_name">
  <h1><%= @patient.first_name %> <%= @patient.last_name %></h1>

  <p><strong>CEP:</strong> <%= @patient.registration_number %></p>
  <p><strong>Data de Nascimento:</strong> <%= @patient.birth_date %></p>

  <%= link_to "Aplicar Novo Instrumento em #{@patient.first_name}", new_user_applied_instrument_path(@patient) %>

  <h3>Instrumentos Aplicados:</h3>

  <div class="instrument-grid-wrapper">
    <% @patient.applied_instruments.each_with_index do |applied_instrument, index| %>
      <%= link_to applied_instrument_path(applied_instrument) do%>
        <div class="instrument-grid-item"><%= applied_instrument.instrument.title %></div>
      <% end %>
      <div class="instrument-grid-item"><%= applied_instrument.status %></div>
    <% end %>
  </div>
</div>