config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :instruments, only: %i[index show]
  resources :users, only: %i[index] do
    resources :applied_instruments, only: %i[index new create]
  end

  get 'profile/check_info', to: 'users#check_info', as: 'check_info'
  post 'profile/checked', to: 'users#checked'
  get '/profile/:id', to: 'users#profile', as: 'profile'

  resources :applied_instruments, only: :show do
    post 'finish_instrument', to: 'applied_instruments#finish_instrument'
    resources :evaluated_answers, only: %i[new create]
  end

  resources :evaluated_answers, only: %i[edit update]
end

app/views/pages/home.html.erb
<div class='home-banner'>
  <div class="home-infos">
    <% if user_signed_in? %>
      <% if current_user.psychologist? %>
        <%= link_to 'Ver Instrumentos <i class="fa-solid fa-arrow-right-long"></i>'.html_safe, instruments_path, class: 'btn-home' %>
      <% else %>
        <%= link_to 'Ver Perfil <i class="fa-solid fa-arrow-right-long"></i>'.html_safe, profile_path(current_user), class: 'btn-home' %>
      <% end %>
    <% else %>
      <%= link_to 'Entrar <i class="fa-solid fa-arrow-right-long"></i>'.html_safe, new_user_session_path, class: 'btn-home' %>
    <% end %>
  </div>
  <div class="home-image">
    <%= image_tag 'instrument-home.svg' %>
  </div>
</div>

<div class="home-cards-wrapper">
  <% if user_signed_in? %>
    <% if current_user.psychologist? %>

      <div class="home-card-item">
        <%= link_to new_user_invitation_path do %>
          <h3>Cadastrar Avaliado</h3>
          <div class="d-flex justify-content-between">
            <i class="fa-solid fa-arrow-right-long"></i>
            <%= image_tag 'add_user.svg' %>
          </div>
        <% end %>
      </div>

      <div class="home-card-item">
        <%= link_to instruments_path do %>
          <h3>Lista de Instrumentos Cadastrados</h3>
          <div class="d-flex justify-content-between">
            <i class="fa-solid fa-arrow-right-long"></i>
            <%= image_tag 'instruments.svg' %>
          </div>
        <% end %>
      </div>

      <div class="home-card-item">
        <%= link_to users_path do %>
          <h3>Lista de Avaliados Cadastrados</h3>
          <div class="d-flex justify-content-between">
            <i class="fa-solid fa-arrow-right-long"></i>
            <%= image_tag 'users.svg' %>
          </div>
        <% end %>
      </div>

    <% else %>

      <div class="home-card-item patient">
        <%= link_to profile_path(current_user) do %>
          <h3>Ver Meu Perfil</h3>
          <div class="d-flex justify-content-between">
            <i class="fa-solid fa-arrow-right-long"></i>
            <%= image_tag 'profile.svg' %>
          </div>
        <% end %>
      </div>

      <div class="home-card-item patient">
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do%>
          <h3>Trocar de Conta</h3>
          <div class="d-flex justify-content-between">
            <i class="fa-solid fa-arrow-right-long"></i>
            <%= image_tag 'logout.svg' %>
          </div>
        <% end %>
      </div>

    <% end %>
  <% end %>
</div>