config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :instruments, only: %i[index show]
  resources :users, only: %i[index] do
    resources :applied_instruments, only: %i[index new create]
  end

  get 'profile/check_info', to: 'users#check_info', as: 'check_info'
  post 'profile/checked', to: 'users#checked'
  get '/profile/:id', to: 'users#profile', as: 'profile'

  resources :applied_instruments, only: :show do
    post 'finish_instrument', to: 'applied_instruments#finish_instrument'
    resources :evaluated_answers, only: %i[new create]
  end

  resources :evaluated_answers, only: %i[edit update]
end

app/models/applied_instrument.rb
class AppliedInstrument < ApplicationRecord
  # Associations
  belongs_to :instrument
  belongs_to :user
  has_many :evaluated_answers, dependent: :destroy

  # Validations
  validates :user_id, uniqueness: { scope: :instrument_id }

  # Callbacks
  after_create :send_user_email_notification

  # Enums
  enum status: {
    pending: 0, # quando o avaliado ainda não respondeu o instrumento
    finished: 1 # instrumento concluído
  }

  private

  def send_user_email_notification
    UserMailer.with(user: user).new_instrument.deliver_now
  end
end

app/controllers/applied_instruments_controller.rb
class AppliedInstrumentsController < ApplicationController
  before_action :set_applied_instrument, only: %i[show]
  before_action :set_user, only: %i[index new create]

  def index
    @applied_instruments = policy_scope(AppliedInstrument)
  end

  def show
    @evaluated_answer = EvaluatedAnswer.new
  end

  def new
    @instruments = policy_scope(Instrument)
    @applied_instrument = AppliedInstrument.new

    authorize @applied_instrument
  end

  def create
    @applied_instrument = AppliedInstrument.new(applied_instrument_params)
    @applied_instrument.user = @user
    @applied_instrument.pending!

    authorize @applied_instrument

    if @applied_instrument.save
      redirect_to profile_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def finish_instrument
    @applied_instrument = AppliedInstrument.find(params[:applied_instrument_id])
    @applied_instrument.finished!

    authorize @applied_instrument

    redirect_to profile_path(@applied_instrument.user)
  end

  # def update
  #   respond_to do |format|
  #     if @applied_instrument.update(applied_instrument_params)
  #       format.html { redirect_to @applied_instrument }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def destroy
  #   @applied_instrument.destroy

  #   respond_to do |format|
  #     format.html { redirect_to applied_instruments_path }
  #   end
  # end

  private

  def applied_instrument_params
    params.require(:applied_instrument).permit(:instrument_id)
  end

  def set_applied_instrument
    @applied_instrument = AppliedInstrument.find(params[:id])

    authorize @applied_instrument
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/applied_instruments_helper.rb
module AppliedInstrumentsHelper
  def translate_status(status)
    if status == 'pending'
      'Pendente'
    elsif status == 'finished'
      'Finalizado'
    end
  end
end

app/views/applied_instruments/new.html.erb
<div class="container list">
  <div class="d-flex">
    <%= link_to :back, class: 'back-link' do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
    <% end %>
    <h1>Escolha o Instrumento</h1>
  </div>

  <div class="profile-grid-wrapper">
    <% @instruments.each_with_index do |instrument, index| %>
      <%= link_to instrument_path(instrument) do%>
        <div class="profile-grid-item first-prof"><%= instrument.title %></div>
      <% end %>
      <div class="profile-grid-item second-prof">
        <%= simple_form_for [@user, @applied_instrument], class: 'applied-instruments-form' do |f| %>
          <%= f.input :instrument_id, input_html: { value: instrument.id }, as: :hidden  %>
          <%= button_tag type: 'submit', class: "btn-submit" do %>
              <i class="fa-solid fa-plus" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/applied_instruments/show.html.erb
<div class="container list">
  <div class="d-flex">
    <%= link_to :back, class: 'back-link' do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
    <% end %>
    <h1><%= @applied_instrument.instrument.title %></h1>
  </div>

  <div class="instrument-card">
    <% if current_user.psychologist? %>
      <% if @applied_instrument.finished? %>
        <div class="instrument-card-title mt-3">
          <h4>Respostas do Avaliado: </h4>
        </div>
        <% @applied_instrument.evaluated_answers.each do |ev_answer| %>
          <div class="instrument-card-answers mt-3">
            <p><%= ev_answer.answer.question.description %>: <%= ev_answer.answer.description %></p>
          </div>
        <% end %>

        <div class="instrument-card-result">
          <h4><strong>Resultado Final: <%= @applied_instrument.evaluated_answers.sum { |ev_answer| ev_answer.answer.score }%> pontos</strong></h4>
        </div>
      <% else %>
        <div class="instrument-card-title mt-3">
          <h4>Instrumento Não Finalizado!</h4>
        </div>

        <div class="my-5 d-flex flex-column">
          <%= link_to "Visualizar Instrumento", instrument_path(@applied_instrument.instrument), class: 'mb-3 btn-home' %>
          <%= link_to "Perfil do Avaliado", profile_path(@applied_instrument.user), class: 'btn-home' %>
        </div>

      <% end %>
    <% end %>


    <% if current_user.patient? %>
      <% @applied_instrument.instrument.questions.each do |question| %>
        <div class="instrument-card-answers mt-3">
          <p><%= question.description %>:</p>
          <% if @applied_instrument.evaluated_answers.select { |a| a.answer.question == question }.any? %>
            <%= @applied_instrument.evaluated_answers.select { |a| a.answer.question == question }.first.answer.description %>
          <% else %>
            <%= simple_form_for [@applied_instrument, @evaluated_answer], html: { class: 'form' } do |f| %>
              <%= f.collection_radio_buttons :answer_id, question.answers, :id, :description %>
              <%= button_tag type: 'submit', class: "submit-answer" do %>
                <i class="fa-solid fa-check" aria-hidden="true"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <div class="instrument-card-result">
        <% if @applied_instrument.pending? %>
          <%= link_to 'Finalizar', applied_instrument_finish_instrument_path(@applied_instrument), data: { turbo_method: :post }, class: 'finish-link' %>
        <% else %>
          <h4>Finalizado! <i class="fa-solid fa-check"></i></h4>
        <% end %>
      </div>
    <% end %>
  </div>
</div>